//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.22 at 11:59:38 PM IST 
//


package com.is.cm.core.domain.shop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ACCOUNT_HOLDER_NAME" minOccurs="0"/>
 *         &lt;element ref="{}ACCOUNT_NUMBER" minOccurs="0"/>
 *         &lt;element ref="{}CC_ISSUING_BANK" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountholdername",
    "accountnumber",
    "ccissuingbank"
})
@XmlRootElement(name = "BANK_ACCOUNT")
public class BANKACCOUNT {

    @XmlElement(name = "ACCOUNT_HOLDER_NAME")
    protected String accountholdername;
    @XmlElement(name = "ACCOUNT_NUMBER")
    protected String accountnumber;
    @XmlElement(name = "CC_ISSUING_BANK")
    protected String ccissuingbank;

    /**
     * Gets the value of the accountholdername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTHOLDERNAME() {
        return accountholdername;
    }

    /**
     * Sets the value of the accountholdername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTHOLDERNAME(String value) {
        this.accountholdername = value;
    }

    /**
     * Gets the value of the accountnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNUMBER() {
        return accountnumber;
    }

    /**
     * Sets the value of the accountnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNUMBER(String value) {
        this.accountnumber = value;
    }

    /**
     * Gets the value of the ccissuingbank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCISSUINGBANK() {
        return ccissuingbank;
    }

    /**
     * Sets the value of the ccissuingbank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCISSUINGBANK(String value) {
        this.ccissuingbank = value;
    }

}
