//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.24 at 05:19:36 PM IST 
//


package salesmachine.oim.suppliers.modal.el;

import javax.xml.bind.annotation.XmlRegistry;

import salesmachine.oim.suppliers.modal.el.tracking.ELTrackRequest;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the salesmachine.oim.suppliers.modal.el package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: salesmachine.oim.suppliers.modal.el
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ELTrackRequest }
     * 
     */
    public ELTrackRequest createELTrackRequest() {
        return new ELTrackRequest();
    }

    /**
     * Create an instance of {@link ELTrackRequest.XMLOrders }
     * 
     */
    public ELTrackRequest.XMLOrders createELTrackRequestXMLOrders() {
        return new ELTrackRequest.XMLOrders();
    }

    /**
     * Create an instance of {@link ELTrackRequest.XMLOrders.Order }
     * 
     */
    public ELTrackRequest.XMLOrders.Order createELTrackRequestXMLOrdersOrder() {
        return new ELTrackRequest.XMLOrders.Order();
    }

}
