//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.24 at 06:28:36 PM IST 
//


package salesmachine.oim.stores.modal.volusion.order;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Orders" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="BillingAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillingPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="BillingPostalCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="BillingState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="IsGTSOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OrderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="PaymentMethodID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="PONum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="ShippingMethodID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="ShipResidential" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sOrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="OrderDetails" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OrderDetailID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ProductPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="QtyShipped" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="TotalPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orders"
})
@XmlRootElement(name = "xmldata")
public class Xmldata {

    @XmlElement(name = "Orders")
    protected List<Xmldata.Orders> orders;

    /**
     * Gets the value of the orders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Xmldata.Orders }
     * 
     * 
     */
    public List<Xmldata.Orders> getOrders() {
        if (orders == null) {
            orders = new ArrayList<Xmldata.Orders>();
        }
        return this.orders;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="BillingAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillingPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="BillingPostalCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="BillingState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="IsGTSOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OrderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="PaymentMethodID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="PONum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ShippingMethodID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="ShipResidential" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sOrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="OrderDetails" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OrderDetailID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ProductPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="QtyShipped" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="TotalPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderID",
        "billingAddress1",
        "billingAddress2",
        "billingCity",
        "billingCompanyName",
        "billingCountry",
        "billingFirstName",
        "billingLastName",
        "billingPhoneNumber",
        "billingPostalCode",
        "billingState",
        "customerID",
        "isGTSOrder",
        "orderDate",
        "orderStatus",
        "paymentAmount",
        "paymentMethodID",
        "poNum",
        "shipAddress1",
        "shipAddress2",
        "shipCity",
        "shipCompanyName",
        "shipCountry",
        "shipFirstName",
        "shipLastName",
        "shipPhoneNumber",
        "shippingMethodID",
        "shipPostalCode",
        "shipResidential",
        "shipState",
        "sOrderID",
        "orderDetails"
    })
    public static class Orders {

        @XmlElement(name = "OrderID")
        protected byte orderID;
        @XmlElement(name = "BillingAddress1", required = true)
        protected String billingAddress1;
        @XmlElement(name = "BillingAddress2", required = true)
        protected String billingAddress2;
        @XmlElement(name = "BillingCity", required = true)
        protected String billingCity;
        @XmlElement(name = "BillingCompanyName", required = true)
        protected String billingCompanyName;
        @XmlElement(name = "BillingCountry", required = true)
        protected String billingCountry;
        @XmlElement(name = "BillingFirstName", required = true)
        protected String billingFirstName;
        @XmlElement(name = "BillingLastName", required = true)
        protected String billingLastName;
        @XmlElement(name = "BillingPhoneNumber")
        protected long billingPhoneNumber;
        @XmlElement(name = "BillingPostalCode")
        protected short billingPostalCode;
        @XmlElement(name = "BillingState", required = true)
        protected String billingState;
        @XmlElement(name = "CustomerID")
        protected byte customerID;
        @XmlElement(name = "IsGTSOrder", required = true)
        protected String isGTSOrder;
        @XmlElement(name = "OrderDate", required = true)
        protected String orderDate;
        @XmlElement(name = "OrderStatus", required = true)
        protected String orderStatus;
        @XmlElement(name = "PaymentAmount")
        protected float paymentAmount;
        @XmlElement(name = "PaymentMethodID")
        protected byte paymentMethodID;
        @XmlElement(name = "PONum", required = true)
        protected String poNum;
        @XmlElement(name = "ShipAddress1", required = true)
        protected String shipAddress1;
        @XmlElement(name = "ShipAddress2", required = true)
        protected String shipAddress2;
        @XmlElement(name = "ShipCity", required = true)
        protected String shipCity;
        @XmlElement(name = "ShipCompanyName", required = true)
        protected String shipCompanyName;
        @XmlElement(name = "ShipCountry", required = true)
        protected String shipCountry;
        @XmlElement(name = "ShipFirstName", required = true)
        protected String shipFirstName;
        @XmlElement(name = "ShipLastName", required = true)
        protected String shipLastName;
        @XmlElement(name = "ShipPhoneNumber")
        protected long shipPhoneNumber;
        @XmlElement(name = "ShippingMethodID")
        protected byte shippingMethodID;
        @XmlElement(name = "ShipPostalCode")
        protected short shipPostalCode;
        @XmlElement(name = "ShipResidential", required = true)
        protected String shipResidential;
        @XmlElement(name = "ShipState", required = true)
        protected String shipState;
        protected byte sOrderID;
        @XmlElement(name = "OrderDetails")
        protected List<Xmldata.Orders.OrderDetails> orderDetails;

        /**
         * Gets the value of the orderID property.
         * 
         */
        public byte getOrderID() {
            return orderID;
        }

        /**
         * Sets the value of the orderID property.
         * 
         */
        public void setOrderID(byte value) {
            this.orderID = value;
        }

        /**
         * Gets the value of the billingAddress1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingAddress1() {
            return billingAddress1;
        }

        /**
         * Sets the value of the billingAddress1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingAddress1(String value) {
            this.billingAddress1 = value;
        }

        /**
         * Gets the value of the billingAddress2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingAddress2() {
            return billingAddress2;
        }

        /**
         * Sets the value of the billingAddress2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingAddress2(String value) {
            this.billingAddress2 = value;
        }

        /**
         * Gets the value of the billingCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingCity() {
            return billingCity;
        }

        /**
         * Sets the value of the billingCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingCity(String value) {
            this.billingCity = value;
        }

        /**
         * Gets the value of the billingCompanyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingCompanyName() {
            return billingCompanyName;
        }

        /**
         * Sets the value of the billingCompanyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingCompanyName(String value) {
            this.billingCompanyName = value;
        }

        /**
         * Gets the value of the billingCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingCountry() {
            return billingCountry;
        }

        /**
         * Sets the value of the billingCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingCountry(String value) {
            this.billingCountry = value;
        }

        /**
         * Gets the value of the billingFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingFirstName() {
            return billingFirstName;
        }

        /**
         * Sets the value of the billingFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingFirstName(String value) {
            this.billingFirstName = value;
        }

        /**
         * Gets the value of the billingLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingLastName() {
            return billingLastName;
        }

        /**
         * Sets the value of the billingLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingLastName(String value) {
            this.billingLastName = value;
        }

        /**
         * Gets the value of the billingPhoneNumber property.
         * 
         */
        public long getBillingPhoneNumber() {
            return billingPhoneNumber;
        }

        /**
         * Sets the value of the billingPhoneNumber property.
         * 
         */
        public void setBillingPhoneNumber(long value) {
            this.billingPhoneNumber = value;
        }

        /**
         * Gets the value of the billingPostalCode property.
         * 
         */
        public short getBillingPostalCode() {
            return billingPostalCode;
        }

        /**
         * Sets the value of the billingPostalCode property.
         * 
         */
        public void setBillingPostalCode(short value) {
            this.billingPostalCode = value;
        }

        /**
         * Gets the value of the billingState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingState() {
            return billingState;
        }

        /**
         * Sets the value of the billingState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingState(String value) {
            this.billingState = value;
        }

        /**
         * Gets the value of the customerID property.
         * 
         */
        public byte getCustomerID() {
            return customerID;
        }

        /**
         * Sets the value of the customerID property.
         * 
         */
        public void setCustomerID(byte value) {
            this.customerID = value;
        }

        /**
         * Gets the value of the isGTSOrder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsGTSOrder() {
            return isGTSOrder;
        }

        /**
         * Sets the value of the isGTSOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsGTSOrder(String value) {
            this.isGTSOrder = value;
        }

        /**
         * Gets the value of the orderDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderDate() {
            return orderDate;
        }

        /**
         * Sets the value of the orderDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderDate(String value) {
            this.orderDate = value;
        }

        /**
         * Gets the value of the orderStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderStatus() {
            return orderStatus;
        }

        /**
         * Sets the value of the orderStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderStatus(String value) {
            this.orderStatus = value;
        }

        /**
         * Gets the value of the paymentAmount property.
         * 
         */
        public float getPaymentAmount() {
            return paymentAmount;
        }

        /**
         * Sets the value of the paymentAmount property.
         * 
         */
        public void setPaymentAmount(float value) {
            this.paymentAmount = value;
        }

        /**
         * Gets the value of the paymentMethodID property.
         * 
         */
        public byte getPaymentMethodID() {
            return paymentMethodID;
        }

        /**
         * Sets the value of the paymentMethodID property.
         * 
         */
        public void setPaymentMethodID(byte value) {
            this.paymentMethodID = value;
        }

        /**
         * Gets the value of the poNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPONum() {
            return poNum;
        }

        /**
         * Sets the value of the poNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPONum(String value) {
            this.poNum = value;
        }

        /**
         * Gets the value of the shipAddress1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipAddress1() {
            return shipAddress1;
        }

        /**
         * Sets the value of the shipAddress1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipAddress1(String value) {
            this.shipAddress1 = value;
        }

        /**
         * Gets the value of the shipAddress2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipAddress2() {
            return shipAddress2;
        }

        /**
         * Sets the value of the shipAddress2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipAddress2(String value) {
            this.shipAddress2 = value;
        }

        /**
         * Gets the value of the shipCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipCity() {
            return shipCity;
        }

        /**
         * Sets the value of the shipCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipCity(String value) {
            this.shipCity = value;
        }

        /**
         * Gets the value of the shipCompanyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipCompanyName() {
            return shipCompanyName;
        }

        /**
         * Sets the value of the shipCompanyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipCompanyName(String value) {
            this.shipCompanyName = value;
        }

        /**
         * Gets the value of the shipCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipCountry() {
            return shipCountry;
        }

        /**
         * Sets the value of the shipCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipCountry(String value) {
            this.shipCountry = value;
        }

        /**
         * Gets the value of the shipFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipFirstName() {
            return shipFirstName;
        }

        /**
         * Sets the value of the shipFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipFirstName(String value) {
            this.shipFirstName = value;
        }

        /**
         * Gets the value of the shipLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipLastName() {
            return shipLastName;
        }

        /**
         * Sets the value of the shipLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipLastName(String value) {
            this.shipLastName = value;
        }

        /**
         * Gets the value of the shipPhoneNumber property.
         * 
         */
        public long getShipPhoneNumber() {
            return shipPhoneNumber;
        }

        /**
         * Sets the value of the shipPhoneNumber property.
         * 
         */
        public void setShipPhoneNumber(long value) {
            this.shipPhoneNumber = value;
        }

        /**
         * Gets the value of the shippingMethodID property.
         * 
         */
        public byte getShippingMethodID() {
            return shippingMethodID;
        }

        /**
         * Sets the value of the shippingMethodID property.
         * 
         */
        public void setShippingMethodID(byte value) {
            this.shippingMethodID = value;
        }

        /**
         * Gets the value of the shipPostalCode property.
         * 
         */
        public short getShipPostalCode() {
            return shipPostalCode;
        }

        /**
         * Sets the value of the shipPostalCode property.
         * 
         */
        public void setShipPostalCode(short value) {
            this.shipPostalCode = value;
        }

        /**
         * Gets the value of the shipResidential property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipResidential() {
            return shipResidential;
        }

        /**
         * Sets the value of the shipResidential property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipResidential(String value) {
            this.shipResidential = value;
        }

        /**
         * Gets the value of the shipState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipState() {
            return shipState;
        }

        /**
         * Sets the value of the shipState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipState(String value) {
            this.shipState = value;
        }

        /**
         * Gets the value of the sOrderID property.
         * 
         */
        public byte getSOrderID() {
            return sOrderID;
        }

        /**
         * Sets the value of the sOrderID property.
         * 
         */
        public void setSOrderID(byte value) {
            this.sOrderID = value;
        }

        /**
         * Gets the value of the orderDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Xmldata.Orders.OrderDetails }
         * 
         * 
         */
        public List<Xmldata.Orders.OrderDetails> getOrderDetails() {
            if (orderDetails == null) {
                orderDetails = new ArrayList<Xmldata.Orders.OrderDetails>();
            }
            return this.orderDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OrderDetailID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ProductPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="QtyShipped" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="TotalPrice" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderDetailID",
            "orderID",
            "productCode",
            "productID",
            "productName",
            "productPrice",
            "qtyShipped",
            "quantity",
            "totalPrice"
        })
        public static class OrderDetails {

            @XmlElement(name = "OrderDetailID")
            protected byte orderDetailID;
            @XmlElement(name = "OrderID")
            protected byte orderID;
            @XmlElement(name = "ProductCode", required = true)
            protected String productCode;
            @XmlElement(name = "ProductID")
            protected int productID;
            @XmlElement(name = "ProductName", required = true)
            protected String productName;
            @XmlElement(name = "ProductPrice")
            protected float productPrice;
            @XmlElement(name = "QtyShipped")
            protected byte qtyShipped;
            @XmlElement(name = "Quantity")
            protected byte quantity;
            @XmlElement(name = "TotalPrice")
            protected float totalPrice;

            /**
             * Gets the value of the orderDetailID property.
             * 
             */
            public byte getOrderDetailID() {
                return orderDetailID;
            }

            /**
             * Sets the value of the orderDetailID property.
             * 
             */
            public void setOrderDetailID(byte value) {
                this.orderDetailID = value;
            }

            /**
             * Gets the value of the orderID property.
             * 
             */
            public byte getOrderID() {
                return orderID;
            }

            /**
             * Sets the value of the orderID property.
             * 
             */
            public void setOrderID(byte value) {
                this.orderID = value;
            }

            /**
             * Gets the value of the productCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductCode() {
                return productCode;
            }

            /**
             * Sets the value of the productCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductCode(String value) {
                this.productCode = value;
            }

            /**
             * Gets the value of the productID property.
             * 
             */
            public int getProductID() {
                return productID;
            }

            /**
             * Sets the value of the productID property.
             * 
             */
            public void setProductID(int value) {
                this.productID = value;
            }

            /**
             * Gets the value of the productName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            /**
             * Gets the value of the productPrice property.
             * 
             */
            public float getProductPrice() {
                return productPrice;
            }

            /**
             * Sets the value of the productPrice property.
             * 
             */
            public void setProductPrice(float value) {
                this.productPrice = value;
            }

            /**
             * Gets the value of the qtyShipped property.
             * 
             */
            public byte getQtyShipped() {
                return qtyShipped;
            }

            /**
             * Sets the value of the qtyShipped property.
             * 
             */
            public void setQtyShipped(byte value) {
                this.qtyShipped = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             */
            public byte getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             */
            public void setQuantity(byte value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the totalPrice property.
             * 
             */
            public float getTotalPrice() {
                return totalPrice;
            }

            /**
             * Sets the value of the totalPrice property.
             * 
             */
            public void setTotalPrice(float value) {
                this.totalPrice = value;
            }

        }

    }

}
