package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OimChannelFiles generated by hbm2java
 */
public class OimChannelFiles implements java.io.Serializable {

	private Integer channelFileId;
	private OimFiletypes oimFiletypes;
	private OimChannels oimChannels;
	private Date insertionTm;
	private Date deleteTm;

	public OimChannelFiles() {
	}

	public OimChannelFiles(OimFiletypes oimFiletypes, OimChannels oimChannels,
			Date insertionTm, Date deleteTm) {
		this.oimFiletypes = oimFiletypes;
		this.oimChannels = oimChannels;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
	}

	public Integer getChannelFileId() {
		return this.channelFileId;
	}

	public void setChannelFileId(Integer channelFileId) {
		this.channelFileId = channelFileId;
	}

	public OimFiletypes getOimFiletypes() {
		return this.oimFiletypes;
	}

	public void setOimFiletypes(OimFiletypes oimFiletypes) {
		this.oimFiletypes = oimFiletypes;
	}

	public OimChannels getOimChannels() {
		return this.oimChannels;
	}

	public void setOimChannels(OimChannels oimChannels) {
		this.oimChannels = oimChannels;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

}
