package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OimFileformats generated by hbm2java
 */
public class OimFileformats implements java.io.Serializable {

	private Integer fileformatId;
	private String fileFormatName;
	private Date insertionTm;
	private Date deleteTm;
	private Set oimFiletypeses = new HashSet(0);

	public OimFileformats() {
	}

	public OimFileformats(String fileFormatName, Date insertionTm,
			Date deleteTm, Set oimFiletypeses) {
		this.fileFormatName = fileFormatName;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
		this.oimFiletypeses = oimFiletypeses;
	}

	public Integer getFileformatId() {
		return this.fileformatId;
	}

	public void setFileformatId(Integer fileformatId) {
		this.fileformatId = fileformatId;
	}

	public String getFileFormatName() {
		return this.fileFormatName;
	}

	public void setFileFormatName(String fileFormatName) {
		this.fileFormatName = fileFormatName;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

	public Set getOimFiletypeses() {
		return this.oimFiletypeses;
	}

	public void setOimFiletypeses(Set oimFiletypeses) {
		this.oimFiletypeses = oimFiletypeses;
	}

}
