package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OimFiletypes generated by hbm2java
 */
public class OimFiletypes implements java.io.Serializable {

	private Integer fileTypeId;
	private OimFileformats oimFileformats;
	private String fileTypeName;
	private Date insertionTm;
	private Date deleteTm;
	private Set oimUploadedFileses = new HashSet(0);
	private Set oimFileformatParamses = new HashSet(0);
	private Set oimFileFieldMaps = new HashSet(0);
	private Set oimChannelFileses = new HashSet(0);

	public OimFiletypes() {
	}

	public OimFiletypes(OimFileformats oimFileformats, String fileTypeName,
			Date insertionTm, Date deleteTm, Set oimUploadedFileses,
			Set oimFileformatParamses, Set oimFileFieldMaps,
			Set oimChannelFileses) {
		this.oimFileformats = oimFileformats;
		this.fileTypeName = fileTypeName;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
		this.oimUploadedFileses = oimUploadedFileses;
		this.oimFileformatParamses = oimFileformatParamses;
		this.oimFileFieldMaps = oimFileFieldMaps;
		this.oimChannelFileses = oimChannelFileses;
	}

	public Integer getFileTypeId() {
		return this.fileTypeId;
	}

	public void setFileTypeId(Integer fileTypeId) {
		this.fileTypeId = fileTypeId;
	}

	public OimFileformats getOimFileformats() {
		return this.oimFileformats;
	}

	public void setOimFileformats(OimFileformats oimFileformats) {
		this.oimFileformats = oimFileformats;
	}

	public String getFileTypeName() {
		return this.fileTypeName;
	}

	public void setFileTypeName(String fileTypeName) {
		this.fileTypeName = fileTypeName;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

	public Set getOimUploadedFileses() {
		return this.oimUploadedFileses;
	}

	public void setOimUploadedFileses(Set oimUploadedFileses) {
		this.oimUploadedFileses = oimUploadedFileses;
	}

	public Set getOimFileformatParamses() {
		return this.oimFileformatParamses;
	}

	public void setOimFileformatParamses(Set oimFileformatParamses) {
		this.oimFileformatParamses = oimFileformatParamses;
	}

	public Set getOimFileFieldMaps() {
		return this.oimFileFieldMaps;
	}

	public void setOimFileFieldMaps(Set oimFileFieldMaps) {
		this.oimFileFieldMaps = oimFileFieldMaps;
	}

	public Set getOimChannelFileses() {
		return this.oimChannelFileses;
	}

	public void setOimChannelFileses(Set oimChannelFileses) {
		this.oimChannelFileses = oimChannelFileses;
	}

}
