package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * OimOrderStatuses generated by hbm2java
 */
public class OimOrderStatuses implements java.io.Serializable {

	private Integer statusId;
	private String statusValue;
	private Set oimOrderDetailses = new HashSet(0);

	public OimOrderStatuses() {
	}

	public OimOrderStatuses(Integer statusId) {
		this.statusId = statusId;
	}

	public OimOrderStatuses(Integer statusId, String statusValue,
			Set oimOrderDetailses) {
		this.statusId = statusId;
		this.statusValue = statusValue;
		this.oimOrderDetailses = oimOrderDetailses;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getStatusValue() {
		return this.statusValue;
	}

	public void setStatusValue(String statusValue) {
		this.statusValue = statusValue;
	}

	public Set getOimOrderDetailses() {
		return this.oimOrderDetailses;
	}

	public void setOimOrderDetailses(Set oimOrderDetailses) {
		this.oimOrderDetailses = oimOrderDetailses;
	}

}
