package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OimOrderProcessingRule generated by hbm2java
 */
public class OimOrderProcessingRule implements java.io.Serializable {

	private Integer ruleId;
	private OimChannels oimChannels;
	private Integer processAll;
	private String processWithStatus;
	private Integer updateStoreOrderStatus;
	private Date insertionTm;
	private Date deleteTm;
	private Integer supplierId;
	private String updateWithStatus;

	public OimOrderProcessingRule() {
	}

	public OimOrderProcessingRule(OimChannels oimChannels, Integer processAll,
			String processWithStatus, Integer updateStoreOrderStatus,
			Date insertionTm, Date deleteTm, Integer supplierId,
			String updateWithStatus) {
		this.oimChannels = oimChannels;
		this.processAll = processAll;
		this.processWithStatus = processWithStatus;
		this.updateStoreOrderStatus = updateStoreOrderStatus;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
		this.supplierId = supplierId;
		this.updateWithStatus = updateWithStatus;
	}

	public Integer getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	public OimChannels getOimChannels() {
		return this.oimChannels;
	}

	public void setOimChannels(OimChannels oimChannels) {
		this.oimChannels = oimChannels;
	}

	public Integer getProcessAll() {
		return this.processAll;
	}

	public void setProcessAll(Integer processAll) {
		this.processAll = processAll;
	}

	public String getProcessWithStatus() {
		return this.processWithStatus;
	}

	public void setProcessWithStatus(String processWithStatus) {
		this.processWithStatus = processWithStatus;
	}

	public Integer getUpdateStoreOrderStatus() {
		return this.updateStoreOrderStatus;
	}

	public void setUpdateStoreOrderStatus(Integer updateStoreOrderStatus) {
		this.updateStoreOrderStatus = updateStoreOrderStatus;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public String getUpdateWithStatus() {
		return this.updateWithStatus;
	}

	public void setUpdateWithStatus(String updateWithStatus) {
		this.updateWithStatus = updateWithStatus;
	}

}
