package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * OimSupplierMethodTypes generated by hbm2java
 */
public class OimSupplierMethodTypes implements java.io.Serializable {

	private Integer methodTypeId;
	private String methodTypeName;
	private Set oimSupplierMethodses = new HashSet(0);

	public OimSupplierMethodTypes() {
	}

	public OimSupplierMethodTypes(Integer methodTypeId) {
		this.methodTypeId = methodTypeId;
	}

	public OimSupplierMethodTypes(Integer methodTypeId, String methodTypeName,
			Set oimSupplierMethodses) {
		this.methodTypeId = methodTypeId;
		this.methodTypeName = methodTypeName;
		this.oimSupplierMethodses = oimSupplierMethodses;
	}

	public Integer getMethodTypeId() {
		return this.methodTypeId;
	}

	public void setMethodTypeId(Integer methodTypeId) {
		this.methodTypeId = methodTypeId;
	}

	public String getMethodTypeName() {
		return this.methodTypeName;
	}

	public void setMethodTypeName(String methodTypeName) {
		this.methodTypeName = methodTypeName;
	}

	public Set getOimSupplierMethodses() {
		return this.oimSupplierMethodses;
	}

	public void setOimSupplierMethodses(Set oimSupplierMethodses) {
		this.oimSupplierMethodses = oimSupplierMethodses;
	}

}
