package salesmachine.hibernatedb;

// Generated 7 Jan, 2010 7:01:48 PM by Hibernate Tools 3.2.4.GA

/**
 * VwOimOrders generated by hbm2java
 */
public class VwOimOrders implements java.io.Serializable {

	private VwOimOrdersId id;

	public VwOimOrders() {
	}

	public VwOimOrders(VwOimOrdersId id) {
		this.id = id;
	}

	public VwOimOrdersId getId() {
		return this.id;
	}

	public void setId(VwOimOrdersId id) {
		this.id = id;
	}

}
