//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.22 at 11:59:38 PM IST 
//


package salesmachine.oim.stores.modal.shop.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CU_SHOPPER_FLAG" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cushopperflag"
})
@XmlRootElement(name = "CU_SHOPPER_FLAGS")
public class CUSHOPPERFLAGS {

    @XmlElement(name = "CU_SHOPPER_FLAG")
    protected CUSHOPPERFLAG cushopperflag;

    /**
     * Gets the value of the cushopperflag property.
     * 
     * @return
     *     possible object is
     *     {@link CUSHOPPERFLAG }
     *     
     */
    public CUSHOPPERFLAG getCUSHOPPERFLAG() {
        return cushopperflag;
    }

    /**
     * Sets the value of the cushopperflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link CUSHOPPERFLAG }
     *     
     */
    public void setCUSHOPPERFLAG(CUSHOPPERFLAG value) {
        this.cushopperflag = value;
    }

}
