//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.22 at 11:59:38 PM IST 
//


package salesmachine.oim.stores.modal.shop.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IT_PURCHASE_ID"/>
 *         &lt;element ref="{}IT_SKU"/>
 *         &lt;element ref="{}IT_QUANTITY"/>
 *         &lt;element ref="{}IT_UNIT_PRICE"/>
 *         &lt;element ref="{}IT_SUB_TOTAL"/>
 *         &lt;element ref="{}IT_VID"/>
 *         &lt;element ref="{}SPECIAL_INSTRUCTIONS" minOccurs="0"/>
 *         &lt;element ref="{}IT_DESCRIPTION"/>
 *         &lt;element ref="{}PAGE_NUMBER" minOccurs="0"/>
 *         &lt;element ref="{}IT_SOURCECODE" minOccurs="0"/>
 *         &lt;element ref="{}IT_TAX" minOccurs="0"/>
 *         &lt;element ref="{}IT_SHIPPING" minOccurs="0"/>
 *         &lt;element ref="{}IT_TRACK_NO" minOccurs="0"/>
 *         &lt;element ref="{}IT_EXTENDED_EXCISE_TAX" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itpurchaseid",
    "itsku",
    "itquantity",
    "itunitprice",
    "itsubtotal",
    "itvid",
    "specialinstructions",
    "itdescription",
    "pagenumber",
    "itsourcecode",
    "ittax",
    "itshipping",
    "ittrackno",
    "itextendedexcisetax"
})
@XmlRootElement(name = "ITEM")
public class ITEM {

    @XmlElement(name = "IT_PURCHASE_ID", required = true)
    protected String itpurchaseid;
    @XmlElement(name = "IT_SKU", required = true)
    protected String itsku;
    @XmlElement(name = "IT_QUANTITY", required = true)
    protected String itquantity;
    @XmlElement(name = "IT_UNIT_PRICE", required = true)
    protected String itunitprice;
    @XmlElement(name = "IT_SUB_TOTAL", required = true)
    protected String itsubtotal;
    @XmlElement(name = "IT_VID", required = true)
    protected String itvid;
    @XmlElement(name = "SPECIAL_INSTRUCTIONS")
    protected SPECIALINSTRUCTIONS specialinstructions;
    @XmlElement(name = "IT_DESCRIPTION", required = true)
    protected String itdescription;
    @XmlElement(name = "PAGE_NUMBER")
    protected String pagenumber;
    @XmlElement(name = "IT_SOURCECODE")
    protected String itsourcecode;
    @XmlElement(name = "IT_TAX")
    protected String ittax;
    @XmlElement(name = "IT_SHIPPING")
    protected String itshipping;
    @XmlElement(name = "IT_TRACK_NO")
    protected String ittrackno;
    @XmlElement(name = "IT_EXTENDED_EXCISE_TAX")
    protected String itextendedexcisetax;

    /**
     * Gets the value of the itpurchaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITPURCHASEID() {
        return itpurchaseid;
    }

    /**
     * Sets the value of the itpurchaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITPURCHASEID(String value) {
        this.itpurchaseid = value;
    }

    /**
     * Gets the value of the itsku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITSKU() {
        return itsku;
    }

    /**
     * Sets the value of the itsku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITSKU(String value) {
        this.itsku = value;
    }

    /**
     * Gets the value of the itquantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITQUANTITY() {
        return itquantity;
    }

    /**
     * Sets the value of the itquantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITQUANTITY(String value) {
        this.itquantity = value;
    }

    /**
     * Gets the value of the itunitprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITUNITPRICE() {
        return itunitprice;
    }

    /**
     * Sets the value of the itunitprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITUNITPRICE(String value) {
        this.itunitprice = value;
    }

    /**
     * Gets the value of the itsubtotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITSUBTOTAL() {
        return itsubtotal;
    }

    /**
     * Sets the value of the itsubtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITSUBTOTAL(String value) {
        this.itsubtotal = value;
    }

    /**
     * Gets the value of the itvid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITVID() {
        return itvid;
    }

    /**
     * Sets the value of the itvid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITVID(String value) {
        this.itvid = value;
    }

    /**
     * Gets the value of the specialinstructions property.
     * 
     * @return
     *     possible object is
     *     {@link SPECIALINSTRUCTIONS }
     *     
     */
    public SPECIALINSTRUCTIONS getSPECIALINSTRUCTIONS() {
        return specialinstructions;
    }

    /**
     * Sets the value of the specialinstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPECIALINSTRUCTIONS }
     *     
     */
    public void setSPECIALINSTRUCTIONS(SPECIALINSTRUCTIONS value) {
        this.specialinstructions = value;
    }

    /**
     * Gets the value of the itdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITDESCRIPTION() {
        return itdescription;
    }

    /**
     * Sets the value of the itdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITDESCRIPTION(String value) {
        this.itdescription = value;
    }

    /**
     * Gets the value of the pagenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAGENUMBER() {
        return pagenumber;
    }

    /**
     * Sets the value of the pagenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAGENUMBER(String value) {
        this.pagenumber = value;
    }

    /**
     * Gets the value of the itsourcecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITSOURCECODE() {
        return itsourcecode;
    }

    /**
     * Sets the value of the itsourcecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITSOURCECODE(String value) {
        this.itsourcecode = value;
    }

    /**
     * Gets the value of the ittax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITTAX() {
        return ittax;
    }

    /**
     * Sets the value of the ittax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITTAX(String value) {
        this.ittax = value;
    }

    /**
     * Gets the value of the itshipping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITSHIPPING() {
        return itshipping;
    }

    /**
     * Sets the value of the itshipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITSHIPPING(String value) {
        this.itshipping = value;
    }

    /**
     * Gets the value of the ittrackno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITTRACKNO() {
        return ittrackno;
    }

    /**
     * Sets the value of the ittrackno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITTRACKNO(String value) {
        this.ittrackno = value;
    }

    /**
     * Gets the value of the itextendedexcisetax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITEXTENDEDEXCISETAX() {
        return itextendedexcisetax;
    }

    /**
     * Sets the value of the itextendedexcisetax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITEXTENDEDEXCISETAX(String value) {
        this.itextendedexcisetax = value;
    }

}
