//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.22 at 11:59:38 PM IST 
//


package salesmachine.oim.stores.modal.shop.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SI_TYPE"/>
 *         &lt;element ref="{}SI_PROMPT"/>
 *         &lt;element ref="{}SI_VALUE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sitype",
    "siprompt",
    "sivalue"
})
@XmlRootElement(name = "SPECIAL_INSTRUCTION")
public class SPECIALINSTRUCTION {

    @XmlElement(name = "SI_TYPE", required = true)
    protected String sitype;
    @XmlElement(name = "SI_PROMPT", required = true)
    protected String siprompt;
    @XmlElement(name = "SI_VALUE", required = true)
    protected String sivalue;

    /**
     * Gets the value of the sitype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITYPE() {
        return sitype;
    }

    /**
     * Sets the value of the sitype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITYPE(String value) {
        this.sitype = value;
    }

    /**
     * Gets the value of the siprompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIPROMPT() {
        return siprompt;
    }

    /**
     * Sets the value of the siprompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIPROMPT(String value) {
        this.siprompt = value;
    }

    /**
     * Gets the value of the sivalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIVALUE() {
        return sivalue;
    }

    /**
     * Sets the value of the sivalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIVALUE(String value) {
        this.sivalue = value;
    }

}
