//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.07 at 05:05:43 PM IST 
//


package salesmachine.oim.suppliers.modal.bf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the salesmachine.oim.suppliers.modal.bf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: salesmachine.oim.suppliers.modal.bf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link StatusResponse.StatusInfo }
     * 
     */
    public StatusResponse.StatusInfo createStatusResponseStatusInfo() {
        return new StatusResponse.StatusInfo();
    }

    /**
     * Create an instance of {@link StatusResponse.StatusInfo.Items }
     * 
     */
    public StatusResponse.StatusInfo.Items createStatusResponseStatusInfoItems() {
        return new StatusResponse.StatusInfo.Items();
    }

    /**
     * Create an instance of {@link StatusResponse.StatusInfo.Order }
     * 
     */
    public StatusResponse.StatusInfo.Order createStatusResponseStatusInfoOrder() {
        return new StatusResponse.StatusInfo.Order();
    }

    /**
     * Create an instance of {@link StatusResponse.ErrorResponse }
     * 
     */
    public StatusResponse.ErrorResponse createStatusResponseErrorResponse() {
        return new StatusResponse.ErrorResponse();
    }

    /**
     * Create an instance of {@link StatusResponse.StatusInfo.Items.Item }
     * 
     */
    public StatusResponse.StatusInfo.Items.Item createStatusResponseStatusInfoItemsItem() {
        return new StatusResponse.StatusInfo.Items.Item();
    }

    /**
     * Create an instance of {@link StatusResponse.StatusInfo.Order.ShipAddress }
     * 
     */
    public StatusResponse.StatusInfo.Order.ShipAddress createStatusResponseStatusInfoOrderShipAddress() {
        return new StatusResponse.StatusInfo.Order.ShipAddress();
    }

}
