//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 05:51:43 PM IST 
//


package salesmachine.oim.suppliers.modal.bf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the salesmachine.oim.suppliers.modal.bf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: salesmachine.oim.suppliers.modal.bf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Orderxmlresp }
     * 
     */
    public Orderxmlresp createOrderxmlresp() {
        return new Orderxmlresp();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Items }
     * 
     */
    public Orderxmlresp.Items createOrderxmlrespItems() {
        return new Orderxmlresp.Items();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Order }
     * 
     */
    public Orderxmlresp.Order createOrderxmlrespOrder() {
        return new Orderxmlresp.Order();
    }

    /**
     * Create an instance of {@link Orderxmlresp.ErrorResponse }
     * 
     */
    public Orderxmlresp.ErrorResponse createOrderxmlrespErrorResponse() {
        return new Orderxmlresp.ErrorResponse();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Items.Item }
     * 
     */
    public Orderxmlresp.Items.Item createOrderxmlrespItemsItem() {
        return new Orderxmlresp.Items.Item();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Order.Shipping }
     * 
     */
    public Orderxmlresp.Order.Shipping createOrderxmlrespOrderShipping() {
        return new Orderxmlresp.Order.Shipping();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Order.Processing }
     * 
     */
    public Orderxmlresp.Order.Processing createOrderxmlrespOrderProcessing() {
        return new Orderxmlresp.Order.Processing();
    }

    /**
     * Create an instance of {@link Orderxmlresp.Order.Totals }
     * 
     */
    public Orderxmlresp.Order.Totals createOrderxmlrespOrderTotals() {
        return new Orderxmlresp.Order.Totals();
    }

}
