//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 05:51:43 PM IST 
//


package salesmachine.oim.suppliers.modal.bf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorResponse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MSG" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="order">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="shipping">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ship_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_add" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_add2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_st" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_zip" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="processing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="po_num" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="exp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_via" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_acct" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="inv_notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="inv_num" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="xml_conf" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="xml_action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="totals">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sub_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="disc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="handling" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="exp_fee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ship_amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="inv_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="vend_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="item_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorResponse",
    "order",
    "items"
})
@XmlRootElement(name = "orderxmlresp")
public class Orderxmlresp {

    @XmlElement(name = "ErrorResponse", required = true)
    protected Orderxmlresp.ErrorResponse errorResponse;
    @XmlElement(required = true)
    protected Orderxmlresp.Order order;
    @XmlElement(required = true)
    protected Orderxmlresp.Items items;

    /**
     * Gets the value of the errorResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Orderxmlresp.ErrorResponse }
     *     
     */
    public Orderxmlresp.ErrorResponse getErrorResponse() {
        return errorResponse;
    }

    /**
     * Sets the value of the errorResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orderxmlresp.ErrorResponse }
     *     
     */
    public void setErrorResponse(Orderxmlresp.ErrorResponse value) {
        this.errorResponse = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Orderxmlresp.Order }
     *     
     */
    public Orderxmlresp.Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orderxmlresp.Order }
     *     
     */
    public void setOrder(Orderxmlresp.Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Orderxmlresp.Items }
     *     
     */
    public Orderxmlresp.Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orderxmlresp.Items }
     *     
     */
    public void setItems(Orderxmlresp.Items value) {
        this.items = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MSG" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msg"
    })
    public static class ErrorResponse {

        @XmlElement(name = "MSG")
        protected List<String> msg;

        /**
         * Gets the value of the msg property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the msg property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMSG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getMSG() {
            if (msg == null) {
                msg = new ArrayList<String>();
            }
            return this.msg;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="vend_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="item_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Items {

        @XmlElement(required = true)
        protected Orderxmlresp.Items.Item item;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link Orderxmlresp.Items.Item }
         *     
         */
        public Orderxmlresp.Items.Item getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orderxmlresp.Items.Item }
         *     
         */
        public void setItem(Orderxmlresp.Items.Item value) {
            this.item = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="vend_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="item_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vendId",
            "itemId",
            "qty",
            "action",
            "price"
        })
        public static class Item {

            @XmlElement(name = "vend_id", required = true)
            protected String vendId;
            @XmlElement(name = "item_id", required = true)
            protected String itemId;
            protected byte qty;
            @XmlElement(required = true)
            protected String action;
            protected float price;

            /**
             * Gets the value of the vendId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendId() {
                return vendId;
            }

            /**
             * Sets the value of the vendId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendId(String value) {
                this.vendId = value;
            }

            /**
             * Gets the value of the itemId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemId() {
                return itemId;
            }

            /**
             * Sets the value of the itemId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemId(String value) {
                this.itemId = value;
            }

            /**
             * Gets the value of the qty property.
             * 
             */
            public byte getQty() {
                return qty;
            }

            /**
             * Sets the value of the qty property.
             * 
             */
            public void setQty(byte value) {
                this.qty = value;
            }

            /**
             * Gets the value of the action property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAction() {
                return action;
            }

            /**
             * Sets the value of the action property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAction(String value) {
                this.action = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public float getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPrice(float value) {
                this.price = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="shipping">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ship_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_add" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_add2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_st" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_zip" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="processing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="po_num" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="exp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_via" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_acct" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="inv_notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="inv_num" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="xml_conf" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="xml_action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="totals">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sub_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="disc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="handling" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="exp_fee" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ship_amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="inv_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "shipping",
        "processing",
        "totals"
    })
    public static class Order {

        protected byte id;
        @XmlElement(required = true)
        protected Orderxmlresp.Order.Shipping shipping;
        @XmlElement(required = true)
        protected Orderxmlresp.Order.Processing processing;
        @XmlElement(required = true)
        protected Orderxmlresp.Order.Totals totals;

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(byte value) {
            this.id = value;
        }

        /**
         * Gets the value of the shipping property.
         * 
         * @return
         *     possible object is
         *     {@link Orderxmlresp.Order.Shipping }
         *     
         */
        public Orderxmlresp.Order.Shipping getShipping() {
            return shipping;
        }

        /**
         * Sets the value of the shipping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orderxmlresp.Order.Shipping }
         *     
         */
        public void setShipping(Orderxmlresp.Order.Shipping value) {
            this.shipping = value;
        }

        /**
         * Gets the value of the processing property.
         * 
         * @return
         *     possible object is
         *     {@link Orderxmlresp.Order.Processing }
         *     
         */
        public Orderxmlresp.Order.Processing getProcessing() {
            return processing;
        }

        /**
         * Sets the value of the processing property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orderxmlresp.Order.Processing }
         *     
         */
        public void setProcessing(Orderxmlresp.Order.Processing value) {
            this.processing = value;
        }

        /**
         * Gets the value of the totals property.
         * 
         * @return
         *     possible object is
         *     {@link Orderxmlresp.Order.Totals }
         *     
         */
        public Orderxmlresp.Order.Totals getTotals() {
            return totals;
        }

        /**
         * Sets the value of the totals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orderxmlresp.Order.Totals }
         *     
         */
        public void setTotals(Orderxmlresp.Order.Totals value) {
            this.totals = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="po_num" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="exp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_via" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_acct" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="inv_notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="inv_num" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="xml_conf" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="xml_action" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "poNum",
            "exp",
            "shipVia",
            "shipAcct",
            "invNotes",
            "invNum",
            "xmlConf",
            "xmlAction"
        })
        public static class Processing {

            @XmlElement(name = "po_num")
            protected byte poNum;
            @XmlElement(required = true)
            protected String exp;
            @XmlElement(name = "ship_via", required = true)
            protected String shipVia;
            @XmlElement(name = "ship_acct", required = true)
            protected String shipAcct;
            @XmlElement(name = "inv_notes", required = true)
            protected String invNotes;
            @XmlElement(name = "inv_num")
            protected int invNum;
            @XmlElement(name = "xml_conf")
            protected int xmlConf;
            @XmlElement(name = "xml_action", required = true)
            protected String xmlAction;

            /**
             * Gets the value of the poNum property.
             * 
             */
            public byte getPoNum() {
                return poNum;
            }

            /**
             * Sets the value of the poNum property.
             * 
             */
            public void setPoNum(byte value) {
                this.poNum = value;
            }

            /**
             * Gets the value of the exp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExp() {
                return exp;
            }

            /**
             * Sets the value of the exp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExp(String value) {
                this.exp = value;
            }

            /**
             * Gets the value of the shipVia property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipVia() {
                return shipVia;
            }

            /**
             * Sets the value of the shipVia property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipVia(String value) {
                this.shipVia = value;
            }

            /**
             * Gets the value of the shipAcct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipAcct() {
                return shipAcct;
            }

            /**
             * Sets the value of the shipAcct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipAcct(String value) {
                this.shipAcct = value;
            }

            /**
             * Gets the value of the invNotes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvNotes() {
                return invNotes;
            }

            /**
             * Sets the value of the invNotes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvNotes(String value) {
                this.invNotes = value;
            }

            /**
             * Gets the value of the invNum property.
             * 
             */
            public int getInvNum() {
                return invNum;
            }

            /**
             * Sets the value of the invNum property.
             * 
             */
            public void setInvNum(int value) {
                this.invNum = value;
            }

            /**
             * Gets the value of the xmlConf property.
             * 
             */
            public int getXmlConf() {
                return xmlConf;
            }

            /**
             * Sets the value of the xmlConf property.
             * 
             */
            public void setXmlConf(int value) {
                this.xmlConf = value;
            }

            /**
             * Gets the value of the xmlAction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXmlAction() {
                return xmlAction;
            }

            /**
             * Sets the value of the xmlAction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXmlAction(String value) {
                this.xmlAction = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ship_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_add" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_add2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_st" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_zip" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shipTo",
            "shipContact",
            "shipAdd",
            "shipAdd2",
            "shipCity",
            "shipSt",
            "shipZip"
        })
        public static class Shipping {

            @XmlElement(name = "ship_to", required = true)
            protected String shipTo;
            @XmlElement(name = "ship_contact", required = true)
            protected String shipContact;
            @XmlElement(name = "ship_add", required = true)
            protected String shipAdd;
            @XmlElement(name = "ship_add2", required = true)
            protected String shipAdd2;
            @XmlElement(name = "ship_city", required = true)
            protected String shipCity;
            @XmlElement(name = "ship_st", required = true)
            protected String shipSt;
            @XmlElement(name = "ship_zip")
            protected short shipZip;

            /**
             * Gets the value of the shipTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipTo() {
                return shipTo;
            }

            /**
             * Sets the value of the shipTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipTo(String value) {
                this.shipTo = value;
            }

            /**
             * Gets the value of the shipContact property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipContact() {
                return shipContact;
            }

            /**
             * Sets the value of the shipContact property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipContact(String value) {
                this.shipContact = value;
            }

            /**
             * Gets the value of the shipAdd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipAdd() {
                return shipAdd;
            }

            /**
             * Sets the value of the shipAdd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipAdd(String value) {
                this.shipAdd = value;
            }

            /**
             * Gets the value of the shipAdd2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipAdd2() {
                return shipAdd2;
            }

            /**
             * Sets the value of the shipAdd2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipAdd2(String value) {
                this.shipAdd2 = value;
            }

            /**
             * Gets the value of the shipCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipCity() {
                return shipCity;
            }

            /**
             * Sets the value of the shipCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipCity(String value) {
                this.shipCity = value;
            }

            /**
             * Gets the value of the shipSt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipSt() {
                return shipSt;
            }

            /**
             * Sets the value of the shipSt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipSt(String value) {
                this.shipSt = value;
            }

            /**
             * Gets the value of the shipZip property.
             * 
             */
            public short getShipZip() {
                return shipZip;
            }

            /**
             * Sets the value of the shipZip property.
             * 
             */
            public void setShipZip(short value) {
                this.shipZip = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sub_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="disc" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="handling" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="exp_fee" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ship_amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="inv_total" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subTotal",
            "disc",
            "handling",
            "expFee",
            "shipAmt",
            "tax",
            "invTotal"
        })
        public static class Totals {

            @XmlElement(name = "sub_total")
            protected float subTotal;
            protected byte disc;
            protected float handling;
            @XmlElement(name = "exp_fee", required = true)
            protected String expFee;
            @XmlElement(name = "ship_amt")
            protected float shipAmt;
            @XmlElement(required = true)
            protected String tax;
            @XmlElement(name = "inv_total")
            protected float invTotal;

            /**
             * Gets the value of the subTotal property.
             * 
             */
            public float getSubTotal() {
                return subTotal;
            }

            /**
             * Sets the value of the subTotal property.
             * 
             */
            public void setSubTotal(float value) {
                this.subTotal = value;
            }

            /**
             * Gets the value of the disc property.
             * 
             */
            public byte getDisc() {
                return disc;
            }

            /**
             * Sets the value of the disc property.
             * 
             */
            public void setDisc(byte value) {
                this.disc = value;
            }

            /**
             * Gets the value of the handling property.
             * 
             */
            public float getHandling() {
                return handling;
            }

            /**
             * Sets the value of the handling property.
             * 
             */
            public void setHandling(float value) {
                this.handling = value;
            }

            /**
             * Gets the value of the expFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpFee() {
                return expFee;
            }

            /**
             * Sets the value of the expFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpFee(String value) {
                this.expFee = value;
            }

            /**
             * Gets the value of the shipAmt property.
             * 
             */
            public float getShipAmt() {
                return shipAmt;
            }

            /**
             * Sets the value of the shipAmt property.
             * 
             */
            public void setShipAmt(float value) {
                this.shipAmt = value;
            }

            /**
             * Gets the value of the tax property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTax() {
                return tax;
            }

            /**
             * Sets the value of the tax property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTax(String value) {
                this.tax = value;
            }

            /**
             * Gets the value of the invTotal property.
             * 
             */
            public float getInvTotal() {
                return invTotal;
            }

            /**
             * Sets the value of the invTotal property.
             * 
             */
            public void setInvTotal(float value) {
                this.invTotal = value;
            }

        }

    }

}
