package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OimFields generated by hbm2java
 */
public class OimFields implements java.io.Serializable {

	private Integer fieldId;
	private String fieldName;
	private String fieldDesc;
	private Date insertionTm;
	private Date deleteTm;
	private Set oimFileFieldMaps = new HashSet(0);

	public OimFields() {
	}

	public OimFields(String fieldName, String fieldDesc, Date insertionTm,
			Date deleteTm, Set oimFileFieldMaps) {
		this.fieldName = fieldName;
		this.fieldDesc = fieldDesc;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
		this.oimFileFieldMaps = oimFileFieldMaps;
	}

	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldDesc() {
		return this.fieldDesc;
	}

	public void setFieldDesc(String fieldDesc) {
		this.fieldDesc = fieldDesc;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

	public Set getOimFileFieldMaps() {
		return this.oimFileFieldMaps;
	}

	public void setOimFileFieldMaps(Set oimFileFieldMaps) {
		this.oimFileFieldMaps = oimFileFieldMaps;
	}

}
