package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

/**
 * OimSuppliers generated by hbm2java
 */
public class OimSuppliers implements java.io.Serializable {


  private static final long serialVersionUID = 1L;
  private Integer supplierId;
	private String supplierName;
	private Integer isCustom;
	private Date insertionTm;
	private Date deleteTm;
	private String description;
	private String className;
	private String defaultSkuPrefix;
	private Set<OimSupplierMethods> oimSupplierMethodses = new TreeSet<OimSupplierMethods>();
	private Set oimVendorsuppOrderhistories = new HashSet(0);
	private Set oimOrderDetailses = new HashSet(0);
	private Set oimVendorSupplierses = new HashSet(0);
	private Set oimChannelSupplierMaps = new HashSet(0);

	public OimSuppliers() {
	}

	public OimSuppliers(String supplierName, Integer isCustom,
			Date insertionTm, Date deleteTm, String description,
			Set oimSupplierMethodses, Set oimVendorsuppOrderhistories,
			Set oimOrderDetailses, Set oimVendorSupplierses,
			Set oimChannelSupplierMaps) {
		this.supplierName = supplierName;
		this.isCustom = isCustom;
		this.insertionTm = insertionTm;
		this.deleteTm = deleteTm;
		this.description = description;
		this.oimSupplierMethodses = oimSupplierMethodses;
		this.oimVendorsuppOrderhistories = oimVendorsuppOrderhistories;
		this.oimOrderDetailses = oimOrderDetailses;
		this.oimVendorSupplierses = oimVendorSupplierses;
		this.oimChannelSupplierMaps = oimChannelSupplierMaps;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public Integer getIsCustom() {
		return this.isCustom;
	}

	public void setIsCustom(Integer isCustom) {
		this.isCustom = isCustom;
	}

	public Date getInsertionTm() {
		return this.insertionTm;
	}

	public void setInsertionTm(Date insertionTm) {
		this.insertionTm = insertionTm;
	}

	public Date getDeleteTm() {
		return this.deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getOimSupplierMethodses() {
		return this.oimSupplierMethodses;
	}

	public void setOimSupplierMethodses(Set oimSupplierMethodses) {
		this.oimSupplierMethodses = oimSupplierMethodses;
	}

	public Set getOimVendorsuppOrderhistories() {
		return this.oimVendorsuppOrderhistories;
	}

	public void setOimVendorsuppOrderhistories(Set oimVendorsuppOrderhistories) {
		this.oimVendorsuppOrderhistories = oimVendorsuppOrderhistories;
	}

	public Set getOimOrderDetailses() {
		return this.oimOrderDetailses;
	}

	public void setOimOrderDetailses(Set oimOrderDetailses) {
		this.oimOrderDetailses = oimOrderDetailses;
	}

	public Set getOimVendorSupplierses() {
		return this.oimVendorSupplierses;
	}

	public void setOimVendorSupplierses(Set oimVendorSupplierses) {
		this.oimVendorSupplierses = oimVendorSupplierses;
	}

	public Set getOimChannelSupplierMaps() {
		return this.oimChannelSupplierMaps;
	}

	public void setOimChannelSupplierMaps(Set oimChannelSupplierMaps) {
		this.oimChannelSupplierMaps = oimChannelSupplierMaps;
	}

  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((insertionTm == null) ? 0 : insertionTm.hashCode());
    result = prime * result + ((supplierId == null) ? 0 : supplierId.hashCode());
    result = prime * result + ((supplierName == null) ? 0 : supplierName.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    OimSuppliers other = (OimSuppliers) obj;
    if (insertionTm == null) {
      if (other.insertionTm != null)
        return false;
    } else if (!insertionTm.equals(other.insertionTm))
      return false;
    if (supplierId == null) {
      if (other.supplierId != null)
        return false;
    } else if (!supplierId.equals(other.supplierId))
      return false;
    if (supplierName == null) {
      if (other.supplierName != null)
        return false;
    } else if (!supplierName.equals(other.supplierName))
      return false;
    return true;
  }

  public String getDefaultSkuPrefix() {
    return defaultSkuPrefix;
  }

  public void setDefaultSkuPrefix(String defaultSkuPrefix) {
    this.defaultSkuPrefix = defaultSkuPrefix;
  }
  


}
