package salesmachine.hibernatedb;


/**
* OimSupplierMethods generated by hbm2java
*/
public class OimSupplierShippingMethods implements java.io.Serializable {

	private Integer id;
	private OimSuppliers oimSuppliers;
	private String shippingName;
	private String shippingCode;
	public Integer specificVendorId;

	public OimSupplierShippingMethods() {
	}

	public OimSupplierShippingMethods(OimSuppliers oimSuppliers, String shippingName, String shippingCode) {
		this.oimSuppliers = oimSuppliers;
		this.shippingName = shippingName;
		this.shippingCode = shippingCode;
	}

	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public OimSuppliers getOimSuppliers() {
		return this.oimSuppliers;
	}

	public void setOimSuppliers(OimSuppliers oimSuppliers) {
		this.oimSuppliers = oimSuppliers;
	}

	public String getShippingName() {
		return this.shippingName;
	}

	public void setShippingName(String shippingName) {
		this.shippingName = shippingName;
	}

	public String getShippingCode() {
		return this.shippingCode;
	}

	public void setShippingCode(String shippingCode) {
		this.shippingCode = shippingCode;
	}

	public Integer getSpecificVendorId() {
		return this.specificVendorId;
	}

	public void setSpecificVendorId(Integer vendorId) {
		this.specificVendorId = vendorId;
	}
}
