package salesmachine.hibernatedb;

// Generated 30 Mar, 2010 7:26:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OimVendorsuppOrderhistory generated by hbm2java
 */
public class OimVendorsuppOrderhistory implements java.io.Serializable {

	private Integer vsoHistoryId;
	private Vendors vendors;
	private OimSuppliers oimSuppliers;
	private Date processingTm;
	private Integer errorCode;
	private String description;
	private Date deleteTm;

	public OimVendorsuppOrderhistory() {
	}

	public OimVendorsuppOrderhistory(Vendors vendors,
			OimSuppliers oimSuppliers, Date processingTm, Integer errorCode,
			String description) {
		this.vendors = vendors;
		this.oimSuppliers = oimSuppliers;
		this.processingTm = processingTm;
		this.errorCode = errorCode;
		this.description = description;
	}

	public Integer getVsoHistoryId() {
		return this.vsoHistoryId;
	}

	public void setVsoHistoryId(Integer vsoHistoryId) {
		this.vsoHistoryId = vsoHistoryId;
	}

	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	public OimSuppliers getOimSuppliers() {
		return this.oimSuppliers;
	}

	public void setOimSuppliers(OimSuppliers oimSuppliers) {
		this.oimSuppliers = oimSuppliers;
	}

	public Date getProcessingTm() {
		return this.processingTm;
	}

	public void setProcessingTm(Date processingTm) {
		this.processingTm = processingTm;
	}

	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDeleteTm() {
		return deleteTm;
	}

	public void setDeleteTm(Date deleteTm) {
		this.deleteTm = deleteTm;
	}

}
