//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 02:42:53 PM IST 
//


package salesmachine.oim.suppliers.modal.hg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the salesmachine.oim.suppliers.modal.hg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: salesmachine.oim.suppliers.modal.hg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrackingData }
     * 
     */
    public TrackingData createTrackingData() {
        return new TrackingData();
    }

    /**
     * Create an instance of {@link TrackingData.PO }
     * 
     */
    public TrackingData.PO createTrackingDataPO() {
        return new TrackingData.PO();
    }

    /**
     * Create an instance of {@link TrackingData.POTracking }
     * 
     */
    public TrackingData.POTracking createTrackingDataPOTracking() {
        return new TrackingData.POTracking();
    }

}
