<%@ page language="java" contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags"%>
<t:openpage>
	<jsp:attribute name="maincontent">
		<div class="main-container-inner">
			<div class="page-header">
				<h1>
					Terms of Service &amp; Privacy Policy<small><i
						class="ace-icon fa fa-angle-double-right"></i>
					</small>
				</h1>
			</div>
			<div class="container">
				<div class="row">
					<p>This user agreement specifies the terms and conditions under which Inventory Source, LLC agrees to provide you with access to inventory and/or order information (“the Information”). If you want to access Inventory Source, LLC's “Order Management Utility” also known as “Channel Manager” to centralize access to online inventory and/or order details and use the automated inventory updating or use the other services we provide (collectively, “Services”) you must accept this user agreement (“Agreement”) in its entirety, including all of its terms and conditions.</p>
					<p>
						We may amend this Agreement at any time by posting the amended terms and conditions on the Inventory Source Order Management Utility's website. Unless otherwise indicated, all amended terms shall automatically be effective fourteen (14) days after they are initially posted, and your continued use of our Services indicates your acceptance of the amended terms. You are responsible for reviewing and becoming familiar with any changes.
					</p>
					<p>
						Inventory Source, LLC, in its sole discretion, may add, delete, or modify some or all of the features of the Information or Services at any time.
					</p>
					<h2>1. Eligibility; Registration.</h2> 
					<p>
						<strong>1.1</strong> Use of the Services is limited to parties that lawfully can enter into and form contracts under applicable law. Without limiting the foregoing, the Services are not available to minors. Further, the Services are not available to parties whose use of the Services has been suspended or terminated.</p>
					<p>
						<strong>1.2</strong> To use the Services, you must submit a complete registration form on behalf of yourself or the corporation, partnership or other legal entity that will be using the Services. By accepting this Agreement, you represent that (a) you are eighteen (18) or older and, if applicable, (b) you are authorized to sign for and bind the corporation, partnership or other legal entity that will be using the Services. You shall provide current, complete and accurate registration information (including email address and credit card information), and then update the information as required to keep the registration information current, complete and accurate.</p>
					<p>
						<strong>1.3</strong> As a subscription service, Inventory Source, LLC will collect payment information from you during the account setup. By providing such payment methods to Inventory Source, LLC, you are explicitly authorizing Inventory Source, LLC to charge one or more of these methods as fees are due.</p>
					<h2>2. Fees and Payment Terms.</h2>
					<p>
						<strong>2.1</strong> The fees are set forth in the Inventory Source Order Management Utility Fee Schedule and Payment Terms and are sent to you when you register and are posted on our site. All registered accounts start off as a free account with no additional data services and will remain this way until a data service is added by you, the user. When you add a data service to your account directly, the current cost will also show before you confirm the addition. Changes to fees and payment terms are effective immediately unless otherwise indicated, and it is your responsibility to check for any changes, but we will also update the changes on our site and alert our member network of the change by sending you a notice to your email ID on file. You agree to pay us for using our services in accordance with our then current Fee Schedule. All fees are payable in U.S. Dollars and will not be treated as paid until actually received by Inventory Source, LLC in same-day and freely available funds. Failure to pay any amounts when due may, in Inventory Source, LLC’s sole discretion, result in your account being suspended or terminated.</p>
					<p>
						<strong>2.2</strong> Any claims for refunds or other adjustments to charges on your account must be submitted in writing. Any claim must be submitted within 30 days of the date such charges are placed on your account.</p>
					<p>
						<strong>2.3</strong> Users who do not complete the registration and agree to the terms directly through the website can agree to the Inventory Source Order Management Utility Fee Schedule and Payment Terms directly by downloading the User Terms &amp; Agreement document provided by Inventory Source, LLC and submitting their agreement via fax back to Inventory Source, LLC.</p>
					<h2>3. User Conduct.</h2>
					<p>
						<strong>3.1</strong> You agree to comply with all applicable laws, statutes, ordinances and regulations related to use of the Services. You may not use our Services to engage in fraud or other illegal activity, or to infringe the intellectual property rights of others.</p>
					<p>
						<strong>3.2</strong> You agree to comply with the terms and conditions of all agreements you have with third parties, including providers of drop ship Inventory, as such terms and conditions relate to use of the Services including, without limitation, terms and conditions related to types of items that may be sold or restrictions on concurrent sales.</p>
					<p>
						<strong>3.3</strong> You agree that you will not use any device, software or routine to interfere or attempt to interfere with the proper working of the Site or any transaction conducted on the Site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure or limits our ability to provide the Services. You agree that you will not collect, copy, reproduce, alter, modify, create derivative works, or publicly display any content or information (except for Your Materials) from the Site without the prior expressed written permission of Inventory Source, LLC or the appropriate third party. You agree that you will not use any robot, spider, or other automatic device or routine to access or interface with the Site.</p>
					<h2>4. Inventory Source, LLC and Third-Party Intellectual Property.</h2>
					<p>
						<strong>4.1</strong> All content included or available on the Site, such as advertisements, text, graphics, logos, button icons, images, audio clips and software, is the property of Inventory Source, LLC and/or third parties and is protected by copyrights, trademarks or other intellectual and proprietary rights. The compilation (meaning the collection, arrangement and assembly) of all content on the Site is the exclusive property of Inventory Source, LLC and/or its licensors, suppliers and distributors and is protected by copyrights or other intellectual and proprietary rights. All software used on the Site is the property of Inventory Source, LLC and/or its software suppliers or distributors and is protected by copyrights, patents or other intellectual and proprietary rights.</p>
					<p>
						<strong>4.2</strong> Subject to the terms and conditions of this Agreement, Inventory Source, LLC grants a limited license to you to make personal use of the Site and the Services only for their intended purposes. This license expressly excludes any resale of the Site and the Services, making any derivative of the Site or the Services, the collection and use of other users’ email addresses or other materials (for example, advertisements), or any data extraction or data mining whatsoever, except with the express consent of the owner of such materials.</p>
					<p>
						<strong>4.3</strong> Inventory Source, LLC retains all right, title, and interest in and to its trademarks, service marks and trade names worldwide (collectively, the “Marks”). You shall only use Inventory Source, LLC’s Marks with the express permission of Inventory Source, LLC and then only in the manner authorized. Under no circumstances may you alter, modify, or change Inventory Source, LLC’s Marks.</p>
					<h2>5. Suspension and Termination.</h2>
					<p>Without limiting other remedies, we may immediately issue a warning, temporarily suspend, indefinitely suspend, or terminate your access to the Site and Services if you breach any of the terms of this Agreement or if you take any actions that, in our sole judgment, may cause legal liability for or claims against you, our users, or us. In the event Inventory Source, LLC suspends or terminates your access to the Site or Services, you acknowledge that you may be denied any further access to the Site.</p>
					<h2>6. Privacy.</h2>
					<p>Inventory Source, LLC is committed to protecting your privacy and we will only use and disclose your information in accordance with our then current Privacy Policy which is incorporated herein by reference.</p>
					<h2>7. Warranty Disclaimer.</h2>
					<p>THE SITE AND THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. INVENTORY SOURCE, LLC AND OUR SUPPLIERS OR DISTRIBUTORS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS, IMPLIED OR STATUTORY. INVENTORY SOURCE, LLC AND OUR SUPPLIERS OR DISTRIBUTORS SPECIFICALLY DISCLAIM ALL WARRANTIES INCLUDING WITHOUT LIMITATION:</p>
					<p>(A) THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT;</p>
					<p>(B) THAT THE SITE OR THE SERVICES WILL MEET YOUR REQUIREMENTS, WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE OR OPERATE WITHOUT ERROR;</p>
					<p>(C) ANY IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OF TRADE; AND</p>
					<p>(D) ANY OBLIGATION, LIABILITY, RIGHT, CLAIM OR REMEDY IN TORT, WHETHER OR NOT ARISING FROM THE NEGLIGENCE OF INVENTORY SOURCE, LLC OR OUR SUPPLIERS OR DISTRIBUTORS.</p>
					<p>Some states do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not fully apply to you. You may also have other legal rights which vary from state to state.</p>
					<h2>8. General Release.</h2>
					<p>
						<strong>8.1</strong> BECAUSE INVENTORY SOURCE, LLC AND OUR SUPPLIERS OR DISTRIBUTORS ARE NOT INVOLVED IN DEALINGS BETWEEN OUR USERS OR BETWEEN OUR USERS AND MARKETPLACE USERS, IF A DISPUTE ARISES BETWEEN YOU AND ANOTHER PARTY, YOU RELEASE INVENTORY SOURCE, LLC (AND ITS AGENTS AND EMPLOYEES, SUPPLIERS AND DISTRIBUTORS) FROM CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES. FURTHER, YOU WAIVE ANY RIGHTS YOU MAY HAVE UNDER CALIFORNIA CIVIL CODE 542 (OR ANY OTHER SIMILAR STATUTE) WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR A THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”</p>
					<p>
						<strong>8.2</strong> YOU ACKNOWLEDGE AND AGREE THAT INVENTORY SOURCE, LLC IS NOT RESPONSIBLE FOR THE AVAILABILITY OF SUPPLIERS OR YOUR SALES CHANNEL AS DEFINED BY A WEBSITE URL OR MARKETPLACE ADDED IN YOUR INVENTORY SOURCE ORDER MANAGEMENT UTILITY, AND DOES NOT ENDORSE AND IS NOT RESPONSIBLE OR LIABLE FOR ANY SERVICES, CONTENT, ADVERTISING, PRODUCTS OR OTHER MATERIALS ON OR AVAILABLE FROM SUCH SUPPLIERS OR YOUR SALES CHANNELS. YOU AGREE THAT INVENTORY SOURCE, LLC SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH THE USE OF OR RELIANCE ON ANY SUCH SERVICES, CONTENT, ADVERTISING, PRODUCTS OR OTHER MATERIALS.</p>
					<p>
						<strong>8.3</strong> YOU ACKNOWLEDGE AND AGREE THAT INVENTORY SOURCE, LLC DOES NOT CONTROL AND IS NOT RESPONSIBLE FOR INFORMATION PROVIDED BY OTHER USERS WHICH IS MADE AVAILABLE ON THE SITE. YOU MAY FIND OTHER USER’S INFORMATION TO BE OFFENSIVE, HARMFUL, INACCURATE OR DECEPTIVE. YOU AGREE THAT INVENTORY SOURCE, LLC SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH THE USE OF OR RELIANCE ON ANY SUCH INFORMATION.</p>
					<h2>9. Limitation of Liability.</h2>
					<p>UNDER NO CIRCUMSTANCES WILL INVENTORY SOURCE, LLC OR OUR SUPPLIERS AND/OR DISTRIBUTORS OR SALES CHANNELS USED IN THE INVENTORY SOURCE ORDER MANAGEMENT UTILITY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF DATA, CONTENT, FILES, PROFIT OR GOODWILL, OR THE COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES), ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, THE SITE, THE SERVICES, THE INABILITY TO USE THE SERVICES OR THOSE RESULTING FROM ANY GOODS OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH THE SERVICES.</p>
					<h2>10. Indemnity.</h2>
					<p>You hereby agree to, at your own expense, indemnity, defend and hold Inventory Source, LLC and our subsidiaries, affiliates, officers, directors, agents, and employees harmless from and against any loss, cost, damages, liability, or expense arising out of or relating to (a) a third-party claim, action or allegation of infringement, misuse or misappropriation based on information, data, files or other content on the Site; (b) any fraud, manipulation, or other breach of this Agreement by you; (c) any third-party claim, action or allegation brought against Inventory Source, LLC arising out of or relating to a dispute with you over the terms and conditions of an agreement or related to the purchase or sale of any goods or services; (d) your violation of any law or the rights of a third party; or (e) your use, or Inventory Source, LLC’s provision, of the Services or use of your account by any third party. Inventory Source, LLC will have the right to participate in its defense and hire counsel of its choice, at your expense. You will not settle any action or claims on Inventory Source, LLC’s behalf without the prior written consent of Inventory Source, LLC.</p>
					<h2 class="Strong_20_Emphasis">11. Notices.</h2>
					<p>Inventory Source, LLC shall provide notice to you via email to the email address you provide in your registration information. Such notice shall be deemed given 24 hours after it is sent, or earlier if actually received by you earlier. Alternatively, Inventory Source, LLC may choose to provide notice to you via certified or registered mail to the mailing address you provide in your registration information. In such case, notice shall be deemed given 3 days after the date of mailing. You shall provide notice to Inventory Source, LLC via email to support@inventorysource.com.</p>
					<h2>12. Termination.</h2>
					<p>Notwithstanding the notice provision above, you may terminate this Agreement at any time by notifying Inventory Source, LLC via email at support@inventorysource.com. During this process, you may be asked to contact Inventory Source, LLC via telephone during normal business hours to complete the termination and to ensure that the termination process is completed quickly and effectively. If you were registered for any paid services, your last bill from Inventory Source, LLC will be for the month in which you have cancelled the service. Inventory Source, LLC, in its sole discretion, may terminate this Agreement or suspend or terminate your access to the Site or the Services immediately without notice for any reason including, without limitation, for your infringement of the intellectual property rights of others. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, provisions related to intellectual property, warranty disclaimers, general releases, limitations of liability, indemnity and the general provisions.</p>
					<h2>13. General.</h2>
					<p>This Agreement is not assignable, transferable or sublicensable by you without Inventory Source, LLC’s prior written consent, and any such conveyance shall be null and void. Inventory Source, LLC may assign this Agreement in whole or in part. This Agreement shall be governed by and construed in accordance with the laws of the state of Florida without regard to conflicts of laws provisions thereof. The sole jurisdiction and venue for actions related to the subject matter hereof shall be the Florida State and U.S. federal courts having within their jurisdiction the location of Inventory Source, LLC’s principal place of business. In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys’ fees. If any provision of this Agreement is held by a court of competent jurisdiction to be illegal, invalid or unenforceable, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches. This Agreement sets forth the entire understanding and agreement between us with respect to the subject matter hereof. You agree and acknowledge that you are not entering into this agreement in reliance on any statements or representations other than those set forth herein. Should any term or condition be in conflict between this Agreement and any document incorporated by reference into this Agreement, the terms of this Agreement shall control.</p>
				</div>
			</div>
		</div>
	</jsp:attribute></t:openpage>