//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:51:37 PM IST 
//


package salesmachine.oim.stores.modal.volusion.tracking;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="TrackingNumbers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Form" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="Gateway" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="Shipment_Cost" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="ShippingMethodID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="MarkOrderShipped" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="SendShippedEmail" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trackingNumbers"
})
@XmlRootElement(name = "xmldata")
public class VolusionOrderTracking {

    @XmlElement(name = "TrackingNumbers")
    public List<VolusionOrderTracking.TrackingNumbers> trackingNumbers;

    /**
     * Gets the value of the trackingNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackingNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackingNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Xmldata.TrackingNumbers }
     * 
     * 
     */
    public List<VolusionOrderTracking.TrackingNumbers> getTrackingNumbers() {
        if (trackingNumbers == null) {
            trackingNumbers = new ArrayList<VolusionOrderTracking.TrackingNumbers>();
        }
        return this.trackingNumbers;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Form" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="Gateway" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="Shipment_Cost" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="ShippingMethodID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="MarkOrderShipped" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="SendShippedEmail" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form",
        "gateway",
        "orderID",
        "_package",
        "shipDate",
        "shipmentCost",
        "shippingMethodID",
        "trackingNumber",
        "markOrderShipped",
        "sendShippedEmail"
    })
    public static class TrackingNumbers {

        @XmlElement(name = "Form")
        protected Object form;
        @XmlElement(name = "Gateway")
        protected Object gateway;
        @XmlElement(name = "OrderID")
        protected Object orderID;
        @XmlElement(name = "Package")
        protected Object _package;
        @XmlElement(name = "ShipDate")
        protected Object shipDate;
        @XmlElement(name = "Shipment_Cost")
        protected Object shipmentCost;
        @XmlElement(name = "ShippingMethodID")
        protected Object shippingMethodID;
        @XmlElement(name = "TrackingNumber", required = true)
        protected Object trackingNumber;
        @XmlElement(name = "MarkOrderShipped")
        protected Object markOrderShipped;
        @XmlElement(name = "SendShippedEmail")
        protected Object sendShippedEmail;

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setForm(Object value) {
            this.form = value;
        }

        /**
         * Gets the value of the gateway property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getGateway() {
            return gateway;
        }

        /**
         * Sets the value of the gateway property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setGateway(Object value) {
            this.gateway = value;
        }

        /**
         * Gets the value of the orderID property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getOrderID() {
            return orderID;
        }

        /**
         * Sets the value of the orderID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setOrderID(Object value) {
            this.orderID = value;
        }

        /**
         * Gets the value of the package property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPackage() {
            return _package;
        }

        /**
         * Sets the value of the package property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPackage(Object value) {
            this._package = value;
        }

        /**
         * Gets the value of the shipDate property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getShipDate() {
            return shipDate;
        }

        /**
         * Sets the value of the shipDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setShipDate(Object value) {
            this.shipDate = value;
        }

        /**
         * Gets the value of the shipmentCost property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getShipmentCost() {
            return shipmentCost;
        }

        /**
         * Sets the value of the shipmentCost property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setShipmentCost(Object value) {
            this.shipmentCost = value;
        }

        /**
         * Gets the value of the shippingMethodID property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getShippingMethodID() {
            return shippingMethodID;
        }

        /**
         * Sets the value of the shippingMethodID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setShippingMethodID(Object value) {
            this.shippingMethodID = value;
        }

        /**
         * Gets the value of the trackingNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTrackingNumber() {
            return trackingNumber;
        }

        /**
         * Sets the value of the trackingNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTrackingNumber(Object value) {
            this.trackingNumber = value;
        }

        /**
         * Gets the value of the markOrderShipped property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getMarkOrderShipped() {
            return markOrderShipped;
        }

        /**
         * Sets the value of the markOrderShipped property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setMarkOrderShipped(Object value) {
            this.markOrderShipped = value;
        }

        /**
         * Gets the value of the sendShippedEmail property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSendShippedEmail() {
            return sendShippedEmail;
        }

        /**
         * Sets the value of the sendShippedEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSendShippedEmail(Object value) {
            this.sendShippedEmail = value;
        }

    }

}
