//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 05:34:44 PM IST 
//


package salesmachine.oim.suppliers.modal.dh;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="REQUEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LOGIN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="USERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STATUSREQUEST" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PONUM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ORDERNUM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="INVOICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "login",
    "statusrequest"
})
@XmlRootElement(name = "XMLFORMPOST")
public class XMLFORMPOST {

    @XmlElement(name = "REQUEST", required = true)
    protected String request;
    @XmlElement(name = "LOGIN", required = true)
    protected XMLFORMPOST.LOGIN login;
    @XmlElement(name = "STATUSREQUEST")
    protected List<XMLFORMPOST.STATUSREQUEST> statusrequest;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREQUEST() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREQUEST(String value) {
        this.request = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFORMPOST.LOGIN }
     *     
     */
    public XMLFORMPOST.LOGIN getLOGIN() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFORMPOST.LOGIN }
     *     
     */
    public void setLOGIN(XMLFORMPOST.LOGIN value) {
        this.login = value;
    }

    /**
     * Gets the value of the statusrequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusrequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTATUSREQUEST().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLFORMPOST.STATUSREQUEST }
     * 
     * 
     */
    public List<XMLFORMPOST.STATUSREQUEST> getSTATUSREQUEST() {
        if (statusrequest == null) {
            statusrequest = new ArrayList<XMLFORMPOST.STATUSREQUEST>();
        }
        return this.statusrequest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="USERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userid",
        "password"
    })
    public static class LOGIN {

        @XmlElement(name = "USERID", required = true)
        protected String userid;
        @XmlElement(name = "PASSWORD", required = true)
        protected String password;

        /**
         * Gets the value of the userid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSERID() {
            return userid;
        }

        /**
         * Sets the value of the userid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSERID(String value) {
            this.userid = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPASSWORD() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPASSWORD(String value) {
            this.password = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PONUM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ORDERNUM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="INVOICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ponum",
        "ordernum",
        "invoice"
    })
    public static class STATUSREQUEST {

        @XmlElement(name = "PONUM")
        protected String ponum;
        @XmlElement(name = "ORDERNUM")
        protected String ordernum;
        @XmlElement(name = "INVOICE")
        protected String invoice;

        /**
         * Gets the value of the ponum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPONUM() {
            return ponum;
        }

        /**
         * Sets the value of the ponum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPONUM(String value) {
            this.ponum = value;
        }

        /**
         * Gets the value of the ordernum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORDERNUM() {
            return ordernum;
        }

        /**
         * Sets the value of the ordernum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORDERNUM(String value) {
            this.ordernum = value;
        }

        /**
         * Gets the value of the invoice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINVOICE() {
            return invoice;
        }

        /**
         * Sets the value of the invoice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINVOICE(String value) {
            this.invoice = value;
        }

    }

}
