//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 05:37:10 PM IST 
//


package salesmachine.oim.suppliers.modal.dh;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ORDERSTATUS" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PONUM" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="ORDERNUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="INVOICE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="INVTOTAL">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="Tax" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="Freight" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="Handling" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="SubTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SOLDTO">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SHIPTO">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ORDERDETAIL">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DETAILITEM" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="QTYBO" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="VENDOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PACKAGE" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CARRIER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TRACKNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SHIPPED" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SHIPITEM" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SHIPITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SERIALNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderstatus",
    "status"
})
@XmlRootElement(name = "XMLRESPONSE")
public class XMLRESPONSE {

    @XmlElement(name = "ORDERSTATUS")
    protected List<XMLRESPONSE.ORDERSTATUS> orderstatus;
    @XmlElement(name = "STATUS", required = true)
    protected String status;

    /**
     * Gets the value of the orderstatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderstatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getORDERSTATUS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLRESPONSE.ORDERSTATUS }
     * 
     * 
     */
    public List<XMLRESPONSE.ORDERSTATUS> getORDERSTATUS() {
        if (orderstatus == null) {
            orderstatus = new ArrayList<XMLRESPONSE.ORDERSTATUS>();
        }
        return this.orderstatus;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PONUM" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="ORDERNUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="INVOICE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="INVTOTAL">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                 &lt;attribute name="Tax" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="Freight" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="Handling" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="SubTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SOLDTO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SHIPTO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ORDERDETAIL">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DETAILITEM" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="QTYBO" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="VENDOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PACKAGE" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CARRIER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TRACKNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SHIPPED" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SHIPITEM" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SHIPITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SERIALNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "branch",
        "ponum",
        "ordernum",
        "invoice",
        "invtotal",
        "soldto",
        "shipto",
        "orderdetail",
        "_package"
    })
    public static class ORDERSTATUS {

        @XmlElement(name = "DATE", required = true)
        protected String date;
        @XmlElement(name = "BRANCH", required = true)
        protected String branch;
        @XmlElement(name = "PONUM")
        protected short ponum;
        @XmlElement(name = "ORDERNUM")
        protected int ordernum;
        @XmlElement(name = "INVOICE")
        protected int invoice;
        @XmlElement(name = "INVTOTAL", required = true)
        protected XMLRESPONSE.ORDERSTATUS.INVTOTAL invtotal;
        @XmlElement(name = "SOLDTO", required = true)
        protected XMLRESPONSE.ORDERSTATUS.SOLDTO soldto;
        @XmlElement(name = "SHIPTO", required = true)
        protected XMLRESPONSE.ORDERSTATUS.SHIPTO shipto;
        @XmlElement(name = "ORDERDETAIL", required = true)
        protected XMLRESPONSE.ORDERSTATUS.ORDERDETAIL orderdetail;
        @XmlElement(name = "PACKAGE")
        protected List<XMLRESPONSE.ORDERSTATUS.PACKAGE> _package;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDATE() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDATE(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the branch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBRANCH() {
            return branch;
        }

        /**
         * Sets the value of the branch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBRANCH(String value) {
            this.branch = value;
        }

        /**
         * Gets the value of the ponum property.
         * 
         */
        public short getPONUM() {
            return ponum;
        }

        /**
         * Sets the value of the ponum property.
         * 
         */
        public void setPONUM(short value) {
            this.ponum = value;
        }

        /**
         * Gets the value of the ordernum property.
         * 
         */
        public int getORDERNUM() {
            return ordernum;
        }

        /**
         * Sets the value of the ordernum property.
         * 
         */
        public void setORDERNUM(int value) {
            this.ordernum = value;
        }

        /**
         * Gets the value of the invoice property.
         * 
         */
        public int getINVOICE() {
            return invoice;
        }

        /**
         * Sets the value of the invoice property.
         * 
         */
        public void setINVOICE(int value) {
            this.invoice = value;
        }

        /**
         * Gets the value of the invtotal property.
         * 
         * @return
         *     possible object is
         *     {@link XMLRESPONSE.ORDERSTATUS.INVTOTAL }
         *     
         */
        public XMLRESPONSE.ORDERSTATUS.INVTOTAL getINVTOTAL() {
            return invtotal;
        }

        /**
         * Sets the value of the invtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLRESPONSE.ORDERSTATUS.INVTOTAL }
         *     
         */
        public void setINVTOTAL(XMLRESPONSE.ORDERSTATUS.INVTOTAL value) {
            this.invtotal = value;
        }

        /**
         * Gets the value of the soldto property.
         * 
         * @return
         *     possible object is
         *     {@link XMLRESPONSE.ORDERSTATUS.SOLDTO }
         *     
         */
        public XMLRESPONSE.ORDERSTATUS.SOLDTO getSOLDTO() {
            return soldto;
        }

        /**
         * Sets the value of the soldto property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLRESPONSE.ORDERSTATUS.SOLDTO }
         *     
         */
        public void setSOLDTO(XMLRESPONSE.ORDERSTATUS.SOLDTO value) {
            this.soldto = value;
        }

        /**
         * Gets the value of the shipto property.
         * 
         * @return
         *     possible object is
         *     {@link XMLRESPONSE.ORDERSTATUS.SHIPTO }
         *     
         */
        public XMLRESPONSE.ORDERSTATUS.SHIPTO getSHIPTO() {
            return shipto;
        }

        /**
         * Sets the value of the shipto property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLRESPONSE.ORDERSTATUS.SHIPTO }
         *     
         */
        public void setSHIPTO(XMLRESPONSE.ORDERSTATUS.SHIPTO value) {
            this.shipto = value;
        }

        /**
         * Gets the value of the orderdetail property.
         * 
         * @return
         *     possible object is
         *     {@link XMLRESPONSE.ORDERSTATUS.ORDERDETAIL }
         *     
         */
        public XMLRESPONSE.ORDERSTATUS.ORDERDETAIL getORDERDETAIL() {
            return orderdetail;
        }

        /**
         * Sets the value of the orderdetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLRESPONSE.ORDERSTATUS.ORDERDETAIL }
         *     
         */
        public void setORDERDETAIL(XMLRESPONSE.ORDERSTATUS.ORDERDETAIL value) {
            this.orderdetail = value;
        }

        /**
         * Gets the value of the package property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the package property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPACKAGE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMLRESPONSE.ORDERSTATUS.PACKAGE }
         * 
         * 
         */
        public List<XMLRESPONSE.ORDERSTATUS.PACKAGE> getPACKAGE() {
            if (_package == null) {
                _package = new ArrayList<XMLRESPONSE.ORDERSTATUS.PACKAGE>();
            }
            return this._package;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *       &lt;attribute name="Tax" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="Freight" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="Handling" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="SubTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class INVTOTAL {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "Tax")
            protected Byte tax;
            @XmlAttribute(name = "Freight")
            protected Byte freight;
            @XmlAttribute(name = "Handling")
            protected Byte handling;
            @XmlAttribute(name = "SubTotal")
            protected Float subTotal;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the tax property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getTax() {
                return tax;
            }

            /**
             * Sets the value of the tax property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setTax(Byte value) {
                this.tax = value;
            }

            /**
             * Gets the value of the freight property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getFreight() {
                return freight;
            }

            /**
             * Sets the value of the freight property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setFreight(Byte value) {
                this.freight = value;
            }

            /**
             * Gets the value of the handling property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getHandling() {
                return handling;
            }

            /**
             * Sets the value of the handling property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setHandling(Byte value) {
                this.handling = value;
            }

            /**
             * Gets the value of the subTotal property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getSubTotal() {
                return subTotal;
            }

            /**
             * Sets the value of the subTotal property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setSubTotal(Float value) {
                this.subTotal = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DETAILITEM" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="QTYBO" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="VENDOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "detailitem"
        })
        public static class ORDERDETAIL {

            @XmlElement(name = "DETAILITEM")
            protected List<XMLRESPONSE.ORDERSTATUS.ORDERDETAIL.DETAILITEM> detailitem;

            /**
             * Gets the value of the detailitem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the detailitem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDETAILITEM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XMLRESPONSE.ORDERSTATUS.ORDERDETAIL.DETAILITEM }
             * 
             * 
             */
            public List<XMLRESPONSE.ORDERSTATUS.ORDERDETAIL.DETAILITEM> getDETAILITEM() {
                if (detailitem == null) {
                    detailitem = new ArrayList<XMLRESPONSE.ORDERSTATUS.ORDERDETAIL.DETAILITEM>();
                }
                return this.detailitem;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="QTYBO" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="VENDOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "itemno",
                "price",
                "quantity",
                "qtybo",
                "vendor",
                "description"
            })
            public static class DETAILITEM {

                @XmlElement(name = "ITEMNO", required = true)
                protected String itemno;
                @XmlElement(name = "PRICE")
                protected float price;
                @XmlElement(name = "QUANTITY")
                protected byte quantity;
                @XmlElement(name = "QTYBO")
                protected byte qtybo;
                @XmlElement(name = "VENDOR", required = true)
                protected String vendor;
                @XmlElement(name = "DESCRIPTION", required = true)
                protected String description;

                /**
                 * Gets the value of the itemno property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getITEMNO() {
                    return itemno;
                }

                /**
                 * Sets the value of the itemno property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setITEMNO(String value) {
                    this.itemno = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public float getPRICE() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPRICE(float value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public byte getQUANTITY() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQUANTITY(byte value) {
                    this.quantity = value;
                }

                /**
                 * Gets the value of the qtybo property.
                 * 
                 */
                public byte getQTYBO() {
                    return qtybo;
                }

                /**
                 * Sets the value of the qtybo property.
                 * 
                 */
                public void setQTYBO(byte value) {
                    this.qtybo = value;
                }

                /**
                 * Gets the value of the vendor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVENDOR() {
                    return vendor;
                }

                /**
                 * Sets the value of the vendor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVENDOR(String value) {
                    this.vendor = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCRIPTION() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCRIPTION(String value) {
                    this.description = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CARRIER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TRACKNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SHIPPED" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SHIPITEM" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SHIPITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SERIALNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "carrier",
            "service",
            "tracknum",
            "shipped",
            "shipitem"
        })
        public static class PACKAGE {

            @XmlElement(name = "CARRIER", required = true)
            protected String carrier;
            @XmlElement(name = "SERVICE", required = true)
            protected String service;
            @XmlElement(name = "TRACKNUM", required = true)
            protected String tracknum;
            @XmlElement(name = "SHIPPED", required = true)
            protected String shipped;
            @XmlElement(name = "SHIPITEM")
            protected List<XMLRESPONSE.ORDERSTATUS.PACKAGE.SHIPITEM> shipitem;

            /**
             * Gets the value of the carrier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCARRIER() {
                return carrier;
            }

            /**
             * Sets the value of the carrier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCARRIER(String value) {
                this.carrier = value;
            }

            /**
             * Gets the value of the service property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSERVICE() {
                return service;
            }

            /**
             * Sets the value of the service property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSERVICE(String value) {
                this.service = value;
            }

            /**
             * Gets the value of the tracknum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTRACKNUM() {
                return tracknum;
            }

            /**
             * Sets the value of the tracknum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTRACKNUM(String value) {
                this.tracknum = value;
            }

            /**
             * Gets the value of the shipped property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSHIPPED() {
                return shipped;
            }

            /**
             * Sets the value of the shipped property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSHIPPED(String value) {
                this.shipped = value;
            }

            /**
             * Gets the value of the shipitem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the shipitem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSHIPITEM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XMLRESPONSE.ORDERSTATUS.PACKAGE.SHIPITEM }
             * 
             * 
             */
            public List<XMLRESPONSE.ORDERSTATUS.PACKAGE.SHIPITEM> getSHIPITEM() {
                if (shipitem == null) {
                    shipitem = new ArrayList<XMLRESPONSE.ORDERSTATUS.PACKAGE.SHIPITEM>();
                }
                return this.shipitem;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SHIPITEMNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SERIALNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "shipitemno",
                "serialno"
            })
            public static class SHIPITEM {

                @XmlElement(name = "SHIPITEMNO", required = true)
                protected String shipitemno;
                @XmlElement(name = "SERIALNO")
                protected String serialno;

                /**
                 * Gets the value of the shipitemno property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSHIPITEMNO() {
                    return shipitemno;
                }

                /**
                 * Sets the value of the shipitemno property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSHIPITEMNO(String value) {
                    this.shipitemno = value;
                }

                /**
                 * Gets the value of the serialno property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSERIALNO() {
                    return serialno;
                }

                /**
                 * Sets the value of the serialno property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSERIALNO(String value) {
                    this.serialno = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "address",
            "city",
            "state",
            "zip"
        })
        public static class SHIPTO {

            @XmlElement(name = "NAME", required = true)
            protected String name;
            @XmlElement(name = "ADDRESS", required = true)
            protected String address;
            @XmlElement(name = "CITY", required = true)
            protected String city;
            @XmlElement(name = "STATE", required = true)
            protected String state;
            @XmlElement(name = "ZIP")
            protected short zip;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNAME() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNAME(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getADDRESS() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setADDRESS(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCITY() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCITY(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTATE() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTATE(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the zip property.
             * 
             */
            public short getZIP() {
                return zip;
            }

            /**
             * Sets the value of the zip property.
             * 
             */
            public void setZIP(short value) {
                this.zip = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "address",
            "city",
            "state",
            "zip"
        })
        public static class SOLDTO {

            @XmlElement(name = "NAME", required = true)
            protected String name;
            @XmlElement(name = "ADDRESS", required = true)
            protected String address;
            @XmlElement(name = "CITY", required = true)
            protected String city;
            @XmlElement(name = "STATE", required = true)
            protected String state;
            @XmlElement(name = "ZIP")
            protected short zip;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNAME() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNAME(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getADDRESS() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setADDRESS(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCITY() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCITY(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTATE() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTATE(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the zip property.
             * 
             */
            public short getZIP() {
                return zip;
            }

            /**
             * Sets the value of the zip property.
             * 
             */
            public void setZIP(short value) {
                this.zip = value;
            }

        }

    }

}
