//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.30 at 03:18:20 PM IST 
//


package salesmachine.oim.stores.modal.shop.order.status;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}ADI_OS_ORDER_STATUS_DETAIL"/>
 *         &lt;element ref="{}INTERNAL_TEXT"/>
 *         &lt;element ref="{}EXTERNAL_TEXT"/>
 *       &lt;/choice>
 *       &lt;attribute name="INVOICE_NUM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MERCHANT_ORDER_NUM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TRANS_SHIPMENT_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AMAZON_ORDER_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT"
})
@XmlRootElement(name = "ADI_OS_STATUS")
public class ADIOSSTATUS {

    @XmlElementRefs({
        @XmlElementRef(name = "INTERNAL_TEXT", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ADI_OS_ORDER_STATUS_DETAIL", type = ADIOSORDERSTATUSDETAIL.class, required = false),
        @XmlElementRef(name = "EXTERNAL_TEXT", type = JAXBElement.class, required = false)
    })
    protected List<Object> adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT;
    @XmlAttribute(name = "INVOICE_NUM")
    protected String invoicenum;
    @XmlAttribute(name = "MERCHANT_ORDER_NUM")
    protected String merchantordernum;
    @XmlAttribute(name = "TRANS_SHIPMENT_ID")
    protected String transshipmentid;
    @XmlAttribute(name = "AMAZON_ORDER_ID")
    protected String amazonorderid;

    /**
     * Gets the value of the adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADIOSORDERSTATUSDETAILOrINTERNALTEXTOrEXTERNALTEXT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ADIOSORDERSTATUSDETAIL }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getADIOSORDERSTATUSDETAILOrINTERNALTEXTOrEXTERNALTEXT() {
        if (adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT == null) {
            adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT = new ArrayList<Object>();
        }
        return this.adiosorderstatusdetailOrINTERNALTEXTOrEXTERNALTEXT;
    }

    /**
     * Gets the value of the invoicenum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICENUM() {
        return invoicenum;
    }

    /**
     * Sets the value of the invoicenum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICENUM(String value) {
        this.invoicenum = value;
    }

    /**
     * Gets the value of the merchantordernum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMERCHANTORDERNUM() {
        return merchantordernum;
    }

    /**
     * Sets the value of the merchantordernum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMERCHANTORDERNUM(String value) {
        this.merchantordernum = value;
    }

    /**
     * Gets the value of the transshipmentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSSHIPMENTID() {
        return transshipmentid;
    }

    /**
     * Sets the value of the transshipmentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSSHIPMENTID(String value) {
        this.transshipmentid = value;
    }

    /**
     * Gets the value of the amazonorderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMAZONORDERID() {
        return amazonorderid;
    }

    /**
     * Sets the value of the amazonorderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMAZONORDERID(String value) {
        this.amazonorderid = value;
    }

}
