//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.30 at 03:18:20 PM IST 
//


package salesmachine.oim.stores.modal.shop.order.status;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="PURCHASE_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SHIP_DATE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EST_SHIP_DATE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SHIP_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CARRIER_TRACKING_NUM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BILLABLE_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NONBILLABLE_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INTERNAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EXTERNAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SEND_EMAIL_TO_SHOPPER_FLAG" default="N">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="WEIGHT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SIZE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QTY_CHANGE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PRINCIPAL_ADJUSTMENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TAX_ADJUSTMENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SHIPPING_ADJUSTMENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INTERNAL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EXTERNAL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "ADI_OS_ORDER_STATUS_DETAIL")
public class ADIOSORDERSTATUSDETAIL {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "PURCHASE_ID")
    protected String purchaseid;
    @XmlAttribute(name = "SHIP_DATE")
    protected String shipdate;
    @XmlAttribute(name = "EST_SHIP_DATE")
    protected String estshipdate;
    @XmlAttribute(name = "SHIP_METHOD")
    protected String shipmethod;
    @XmlAttribute(name = "CARRIER_TRACKING_NUM")
    protected String carriertrackingnum;
    @XmlAttribute(name = "BILLABLE_AMOUNT")
    protected String billableamount;
    @XmlAttribute(name = "NONBILLABLE_AMOUNT")
    protected String nonbillableamount;
    @XmlAttribute(name = "INTERNAL_STATUS")
    protected String internalstatus;
    @XmlAttribute(name = "EXTERNAL_STATUS")
    protected String externalstatus;
    @XmlAttribute(name = "SEND_EMAIL_TO_SHOPPER_FLAG")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sendemailtoshopperflag;
    @XmlAttribute(name = "WEIGHT")
    protected String weight;
    @XmlAttribute(name = "SIZE")
    protected String size;
    @XmlAttribute(name = "QTY_CHANGE")
    protected String qtychange;
    @XmlAttribute(name = "PRINCIPAL_ADJUSTMENT")
    protected String principaladjustment;
    @XmlAttribute(name = "TAX_ADJUSTMENT")
    protected String taxadjustment;
    @XmlAttribute(name = "SHIPPING_ADJUSTMENT")
    protected String shippingadjustment;
    @XmlAttribute(name = "INTERNAL_TEXT")
    protected String internaltext;
    @XmlAttribute(name = "EXTERNAL_TEXT")
    protected String externaltext;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the purchaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPURCHASEID() {
        return purchaseid;
    }

    /**
     * Sets the value of the purchaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPURCHASEID(String value) {
        this.purchaseid = value;
    }

    /**
     * Gets the value of the shipdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPDATE() {
        return shipdate;
    }

    /**
     * Sets the value of the shipdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPDATE(String value) {
        this.shipdate = value;
    }

    /**
     * Gets the value of the estshipdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESTSHIPDATE() {
        return estshipdate;
    }

    /**
     * Sets the value of the estshipdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESTSHIPDATE(String value) {
        this.estshipdate = value;
    }

    /**
     * Gets the value of the shipmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPMETHOD() {
        return shipmethod;
    }

    /**
     * Sets the value of the shipmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPMETHOD(String value) {
        this.shipmethod = value;
    }

    /**
     * Gets the value of the carriertrackingnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCARRIERTRACKINGNUM() {
        return carriertrackingnum;
    }

    /**
     * Sets the value of the carriertrackingnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCARRIERTRACKINGNUM(String value) {
        this.carriertrackingnum = value;
    }

    /**
     * Gets the value of the billableamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLABLEAMOUNT() {
        return billableamount;
    }

    /**
     * Sets the value of the billableamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLABLEAMOUNT(String value) {
        this.billableamount = value;
    }

    /**
     * Gets the value of the nonbillableamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONBILLABLEAMOUNT() {
        return nonbillableamount;
    }

    /**
     * Sets the value of the nonbillableamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONBILLABLEAMOUNT(String value) {
        this.nonbillableamount = value;
    }

    /**
     * Gets the value of the internalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERNALSTATUS() {
        return internalstatus;
    }

    /**
     * Sets the value of the internalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERNALSTATUS(String value) {
        this.internalstatus = value;
    }

    /**
     * Gets the value of the externalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTERNALSTATUS() {
        return externalstatus;
    }

    /**
     * Sets the value of the externalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTERNALSTATUS(String value) {
        this.externalstatus = value;
    }

    /**
     * Gets the value of the sendemailtoshopperflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENDEMAILTOSHOPPERFLAG() {
        if (sendemailtoshopperflag == null) {
            return "N";
        } else {
            return sendemailtoshopperflag;
        }
    }

    /**
     * Sets the value of the sendemailtoshopperflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENDEMAILTOSHOPPERFLAG(String value) {
        this.sendemailtoshopperflag = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEIGHT() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEIGHT(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIZE() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIZE(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the qtychange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTYCHANGE() {
        return qtychange;
    }

    /**
     * Sets the value of the qtychange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTYCHANGE(String value) {
        this.qtychange = value;
    }

    /**
     * Gets the value of the principaladjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRINCIPALADJUSTMENT() {
        return principaladjustment;
    }

    /**
     * Sets the value of the principaladjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRINCIPALADJUSTMENT(String value) {
        this.principaladjustment = value;
    }

    /**
     * Gets the value of the taxadjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXADJUSTMENT() {
        return taxadjustment;
    }

    /**
     * Sets the value of the taxadjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXADJUSTMENT(String value) {
        this.taxadjustment = value;
    }

    /**
     * Gets the value of the shippingadjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPINGADJUSTMENT() {
        return shippingadjustment;
    }

    /**
     * Sets the value of the shippingadjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPINGADJUSTMENT(String value) {
        this.shippingadjustment = value;
    }

    /**
     * Gets the value of the internaltext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERNALTEXT() {
        return internaltext;
    }

    /**
     * Sets the value of the internaltext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERNALTEXT(String value) {
        this.internaltext = value;
    }

    /**
     * Gets the value of the externaltext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTERNALTEXT() {
        return externaltext;
    }

    /**
     * Sets the value of the externaltext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTERNALTEXT(String value) {
        this.externaltext = value;
    }

}
